apiVersion: v1
kind: Service
metadata:
  name: pizza-postgres
spec:
  selector:
    app: pizza-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-postgres
  template:
    metadata:
      labels:
        app: pizza-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "pizza_user"
            - name: POSTGRES_PASSWORD
              value: "pizza_pass"
            - name: POSTGRES_DB
              value: "pizza_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-pizza-pipeline
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: batch-pizza
              image: batch-pizza:latest
              imagePullPolicy: IfNotPresent
              command: ["python3", "-m", "orchestration.batch_runner"]
              env:
                - name: POSTGRES_HOST
                  value: "pizza-postgres"
                - name: POSTGRES_DB
                  value: "pizza_db"
                - name: POSTGRES_USER
                  value: "pizza_user"
                - name: POSTGRES_PASSWORD
                  value: "pizza_pass"
              volumeMounts:
                - name: logs
                  mountPath: /app/logs
          volumes:
            - name: logs
              emptyDir: {}
